name: pomidor
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  provider: ^6.0.5
  audioplayers: ^0.20.1


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  assets:
    - assets/sounds/work_end.mp3
    - assets/sounds/break_end.mp3